title: Sudbury Tech Cafe
email: email@example.com
description: >- 
  Developer-led talks, lightning round rants, tool swaps, and real-world debugging therapy. Come for the code, stay for the commit confessions.
baseurl: "" 
url: "https://sudbury-tech-cafe.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
